[tools]
go = "1"

# Used for demo GIF
vhs = "latest"

[tasks.lint]
description = "Lint code"
run = '''
go vet ./...
golangci-lint run ./...
'''

[tasks.create-demo]
description = "Create demo GIF"
run = "vhs ./static/demo.tape"

[settings]
quiet = true
